;#######################################################################;
;[PATH];
; destination: str, the complete path save file changing username of windows to custom e.g "C:\Users\UserNameWindows\Documents" to "C:\Users\custom\Documents";

;[FILE];
;name_excel: str, the disered name to save excel file
;name_excel_add_prefix: "add YYYYmm.monthname" at the being of file name
;name_query: name of the query to read. Must be at the same folder of .exe/.py file;
;previous_month: number of previous months to update excel file (delete and get data again from database). OBS the current month are included at ammount;


;[SQL];
;export_type: int;
;    0: read and execute query as writed;
;    1: is the default option. Runs monthly data field must be in query as: datafield BETWEEN custom and custom;
;    2: no querie's filter, read query until where clausule and change it to WHERE 1=1;
;add_current_day: int, ammount of days to add in final date to replace "custom" term of queries;


;[EVALUATE];
;debug: binary, when 1 print messages thought the code to check the execution of main steps;
;logtime: binary, when 1 shows time spended;

; ----- WARNING!!  -----: python is case senstive, all database objects must be writen as typed in database. Type all sql commands in UPPERCASE;
;#######################################################################;

[PATH]
destination = C:\Users\custom\Downloads\dawrf,C:\Users\custom\Downloads\peakaboo

[FILE]
previous_month = 2
name_excel = basefile_name
name_query = chan_to_query_name

[SQL]
export_type = 1
add_current_day = 1

[EVALUATE]
debug = 0
logtime = 1
